# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install requests
          pip install lxml
          pip install beautifulsoup4
          pip install EbookLib
          
      # Runs a single command using the runners shell
      - name: create epub
        run: |
          python3 main.py 八零年代 https://www.ipaoshubaxs.com/122248/ 200
          python3 main.py 重生权势巅峰 https://www.ipaoshubaxs.com/130087/ 500
          python3 main.py 毒蛇把练武的我咬成了修仙者 https://www.ipaoshubaxs.com/125874/ 300
          python3 main.py 凡人修仙从挖矿开始 https://www.ipaoshubaxs.com/133990/ 300
          python3 main.py 重生朱允熥打造大明巅峰 https://www.ipaoshubaxs.com/123305/ 1000
          python3 main.py 我在万倍地球上猎杀外星神明 https://www.ipaoshubaxs.com/268698/ 50
          python3 main.py 修仙我真没想当舔狗 https://www.ipaoshubaxs.com/318018/ 200



      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-generated-file
          path: |
            八零年代.epub
            重生权势巅峰.epub
            毒蛇把练武的我咬成了修仙者.epub
            凡人修仙从挖矿开始.epub
            重生朱允熥打造大明巅峰.epub
            我在万倍地球上猎杀外星神明.epub
            修仙我真没想当舔狗.epub

